### PR TITLE
Add JSON output tests

### PR DESCRIPTION
**Pull request by driftingly**
This PR adds tests to ensure the JSON output files are generated with the correct content and are in the expected shape.

 - JSON output requires models to be published and all translations to be active.
 - JSON output requires artworks to be on view and limits them to 8 for each prompt
 - Adds missing Journey Guide field
 - Fixes issue with artwork title
 - Adds test seeder

**JsonDataTest**

The test file swaps out the `ApiQueryBuilder` for a mock to hijack calls to the `get` method and respond with data from the two mock stub files. This mock data will be used in the test seeder and provide consistent data for testing.

### CODE REVIEW

**Review by zachgarwood — APPROVED** [review]
Nicely done!

**Comment by nikhiltri** [comment]
@driftingly A few questions:

* When I run `php artisan migrate:fresh --seed` on this branch I get the error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'published' in 'field list' (Connection: mysql, SQL: insert into theme_prompt_artworks (theme_prompt_id, artwork_id, activity_template, published, position, updated_at, created_at) values (1, 1, 1, 1, 1, 2024-04-25 21:18:14, 2024-04-25 21:18:14))`
* What do I need to do locally in order to run the tests? Set up a database? Create a `.env.testing` file?

**Comment by driftingly** [comment]
> @driftingly A few questions:
> 
> * When I run `php artisan migrate:fresh --seed` on this branch I get the error: `SQLSTATE[42S22]: Column not found: 1054 Unknown column 'published' in 'field list' (Connection: mysql, SQL: insert into theme_prompt_artworks (theme_prompt_id, artwork_id, activity_template, published, position, updated_at, created_at) values (1, 1, 1, 1, 1, 2024-04-25 21:18:14, 2024-04-25 21:18:14))`
> * What do I need to do locally in order to run the tests? Set up a database? Create a `.env.testing` file?

@nikhiltri - issue with the seeding fixed - I removed `published` from the wrong seeder.
I updated the readme with information on tests and included a composer alias:

```bash
composer test
```

Or you can run directly:

```bash 
./vendor/bin/phpunit
```

Tests use an in memory SQLite database, so no need to set up an additional testing database or environment file.

**Review by zachgarwood — APPROVED** [review]

**Comment by nikhiltri** [comment]
@driftingly Got it. I am able to run the tests locally but I am getting a few errors:

```
......FFFEEE.EEE                                                  16 / 16 (100%)

Time: 00:19.934, Memory: 56.50 MB

There were 6 errors:

1) Tests\Feature\JsonDataTest::only_eight_artworks_are_visible
Error: Call to a member function artworks() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:213
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

2) Tests\Feature\JsonDataTest::only_published_themes_are_public
Error: Call to a member function update() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:231
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

3) Tests\Feature\JsonDataTest::only_published_prompts_are_public
Error: Call to a member function update() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:243
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

4) Tests\Feature\JsonDataTest::themes_require_all_translations_to_be_active
Error: Call to a member function translations() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:272
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

5) Tests\Feature\JsonDataTest::prompts_require_all_translations_to_be_active
Error: Call to a member function translations() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:284
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

6) Tests\Feature\JsonDataTest::prompt_artworks_require_all_translations_to_be_active
Error: Call to a member function artworks() on null

/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:298
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

--

There were 3 failures:

1) Tests\Feature\JsonDataTest::it_provides_themes
Property [themes.0.id] does not match the expected value.
Failed asserting that 21 is identical to 1.

/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/Fluent/Concerns/Matching.php:41
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:112
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:678
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:111
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

2) Tests\Feature\JsonDataTest::it_provides_prompts
Property [themes.0.prompts.0.id] does not match the expected value.
Failed asserting that 97 is identical to 1.

/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/Fluent/Concerns/Matching.php:41
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:148
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:678
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:147
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

3) Tests\Feature\JsonDataTest::it_provides_artworks
Property [themes.0.prompts.0.artworks.0.id] does not match the expected value.
Failed asserting that 1345 is identical to 1.

/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/Fluent/Concerns/Matching.php:41
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:197
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Testing/TestResponse.php:678
/home/vagrant/journeymaker-cms/tests/Feature/JsonDataTest.php:196
/home/vagrant/journeymaker-cms/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php:61

ERRORS!
Tests: 16, Assertions: 400, Errors: 6, Failures: 3.
Script ./vendor/bin/phpunit handling the test event returned with error code 2
```

**Comment by nikhiltri** [comment]
@driftingly I ran `composer install` again, and while there was nothing new to install the tests now pass. Maybe I had something cached that `dump:autload` fixed. So ✅.

**Review by nikhiltri — APPROVED** [review]
Looks good! ⭐

**Pull request merged**
